apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: evanzzell/myproject:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongodb-service"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          value: "root"
        - name: MONGO_PASSWORD
          value: "pass"
        - name: MONGO_AUTH_SOURCE
          value: "admin"
        - name: MONGO_DB_NAME
          value: "mytododb"
